name: "Bug"
description: "버그가 생겼어요 😠"
labels: 버그
body:
  - type: textarea
    attributes:
      label: Describe
      description: |
        버그에 관한 설명을 간단하게 작성해주세요.
      placeholder: |
        매우 심각한 버그에요!

  - type: textarea
    attributes:
      label: How
      description: |
        어떤상황에서 생기는 버그인지 간단하게 설명해주세요.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    attributes:
      label: Environment
      render: shell
      description: |
        버그가 발생한 환경에 대해 설명해주세요!
      placeholder: |
        System:
          OS: macOS 11.4

  - type: textarea
    attributes:
      label: Additional
      description: |
        추가로 할말이 있으신가요?
