name: CachingDependencies

on:
  push:
    branches:
      - develop

env:
  CACHED_DEPENDENCY_PATHS: ${{ github.workspace }}/Tuist/Dependencies

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compute dependency cache key
      id: compute_hash
      run: echo "hash=${{ hashFiles('Tuist/Dependencies.swift') }}" >> $GITHUB_OUTPUT
    - name: Check dependency cache
      uses: actions/cache@v3
      id: cache_dependencies
      with:
        path: ${{ env.CACHED_DEPENDENCY_PATHS }}
        key: ${{ steps.compute_hash.outputs.hash }}
    - name: install tuist
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: bash <(curl -Ls https://install.tuist.io)
    - name: Install dependencies
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: tuist fetch
    outputs:
      dependency_cache_key: ${{ steps.compute_hash.outputs.hash }}
