name: Move version to main branch

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: git merge to main
        run: |
          git config --global user.name 'xquare-admin'
          git config --global user.email 'teamxquare@gmail.com'
          git config pull.rebase false
          git checkout -t origin/main
          echo $(git merge -Xtheirs origin/release -m "🚀 :: Deploy version ${{ env.RELEASE_VERSION }} to AppStore")
          git push
